name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        version: ["1.16.5", "1.18.2", "1.19.2", "1.20.1", "1.21.1"]
            
            
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup release version
      id: release-version
      run: |
        version=$(echo ${{ github.event.release.tag_name }} | cut -d'v' -f2)
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Switch ${{ matrix.version }}
      uses: gradle/gradle-build-action@v2
      with:
        arguments: -Pversion=${{ steps.release-version.outputs.version }} -p "versions/${{ matrix.version }}"

    - name: Build ${{ matrix.version }}
      uses: gradle/gradle-build-action@v2
      env:
        AW_SIGN_ALIAS: ${{ secrets.AW_SIGN_ALIAS }}
        AW_SIGN_KEY_PASS: ${{ secrets.AW_SIGN_KEY_PASS }}
        AW_SIGN_STORE: ${{ secrets.AW_SIGN_STORE }}
        AW_SIGN_STORE_PASS: ${{ secrets.AW_SIGN_STORE_PASS }}
      with:
        arguments: -Pversion=${{ steps.release-version.outputs.version }} build

    - name: Prepare Fabric Artifacts
      run: |
        mkdir -p filtered-fabric-artifacts
        shopt -s extglob
        cp fabric/build/libs/!(*-@(dev-shadow|sources|javadoc)).jar filtered-fabric-artifacts/ || true

    - name: Prepare Forge Artifacts
      run: |
        mkdir -p filtered-forge-artifacts
        shopt -s extglob
        cp forge/build/libs/!(*-@(dev-shadow|sources|javadoc)).jar filtered-forge-artifacts/ || true

    - name: Upload Fabric ${{ matrix.version }} Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fabric-${{ matrix.version }}-${{ steps.release-version.outputs.version }}
        path: filtered-fabric-artifacts

    - name: Upload Forge ${{ matrix.version }} Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: forge-${{ matrix.version }}-${{ steps.release-version.outputs.version }}
        path: filtered-forge-artifacts
